# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameUseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='代码')),
                ('value', models.CharField(max_length=30, verbose_name='机架使用类型')),
            ],
            options={
                'verbose_name': '机架使用类型',
            },
        ),
        migrations.CreateModel(
            name='HouseNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='代码')),
                ('value', models.CharField(max_length=30, verbose_name='机房属性')),
            ],
            options={
                'verbose_name': '机房属性',
            },
        ),
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='代码')),
                ('value', models.CharField(max_length=30, verbose_name='证件类型')),
            ],
            options={
                'verbose_name': '证件类型',
            },
        ),
        migrations.CreateModel(
            name='IpUseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='代码')),
                ('value', models.CharField(max_length=30, verbose_name='IP使用方式')),
            ],
            options={
                'verbose_name': 'IP使用方式',
            },
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='代码')),
                ('value', models.CharField(max_length=30, verbose_name='链路类型')),
            ],
            options={
                'verbose_name': '链路类型',
            },
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='代码')),
                ('value', models.CharField(max_length=30, verbose_name='名称')),
            ],
            options={
                'verbose_name': '上报状态',
            },
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=10, verbose_name='父类')),
                ('key', models.CharField(max_length=10, verbose_name='类型序号')),
                ('value', models.CharField(max_length=30, verbose_name='服务内容名称')),
            ],
            options={
                'verbose_name': '服务内容',
            },
        ),
        migrations.CreateModel(
            name='UnitNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='代码')),
                ('value', models.CharField(max_length=30, verbose_name='单位属性')),
            ],
            options={
                'verbose_name': '单位属性',
            },
        ),
    ]
