# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandOperateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='代码')),
                ('value', models.CharField(max_length=30, verbose_name='名称')),
            ],
            options={
                'verbose_name': '指令操作类型',
            },
        ),
        migrations.CreateModel(
            name='CommandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='代码')),
                ('value', models.CharField(max_length=30, verbose_name='名称')),
            ],
            options={
                'verbose_name': '指令类型',
            },
        ),
        migrations.CreateModel(
            name='RuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, verbose_name='代码')),
                ('value', models.CharField(max_length=30, verbose_name='名称')),
            ],
            options={
                'verbose_name': '规则类型',
            },
        ),
    ]
