# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.BigIntegerField(blank=True, null=True, verbose_name='管理指令ID')),
                ('command_type', models.CharField(blank=True, max_length=1, null=True, verbose_name='指令类型')),
                ('operate_type', models.CharField(blank=True, max_length=1, null=True, verbose_name='操作类型')),
                ('effect_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='生效时间')),
                ('deadline', models.CharField(blank=True, max_length=20, null=True, verbose_name='过期时间')),
                ('unit_licence', models.CharField(blank=True, max_length=20, null=True, verbose_name='经营者编号')),
                ('house', models.CharField(blank=True, max_length=30, null=True, verbose_name='所属机房')),
                ('send_user', models.CharField(blank=True, max_length=30, null=True, verbose_name='下发指令用户名')),
                ('command_origin', models.CharField(blank=True, max_length=20, null=True, verbose_name='指令来源')),
                ('priority', models.CharField(blank=True, max_length=20, null=True, verbose_name='优先级')),
                ('is_write_log', models.CharField(blank=True, max_length=5, null=True, verbose_name='是否记录日志')),
                ('is_report', models.CharField(blank=True, max_length=5, null=True, verbose_name='是否进行上传')),
                ('filter_reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='过滤原因')),
                ('rule_type', models.CharField(blank=True, max_length=1, null=True, verbose_name='规则类型')),
                ('rule_start_value', models.CharField(blank=True, max_length=1, null=True, verbose_name='规则内容起始值')),
                ('rule_end_value', models.CharField(blank=True, max_length=1, null=True, verbose_name='规则内容结束值')),
                ('keyword', models.CharField(blank=True, max_length=1, null=True, verbose_name='关键词匹配范围')),
                ('create_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '管理指令',
            },
        ),
    ]
