# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='keyword',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='关键词匹配范围'),
        ),
        migrations.AlterField(
            model_name='command',
            name='rule_end_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='规则内容结束值'),
        ),
        migrations.AlterField(
            model_name='command',
            name='rule_start_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='规则内容起始值'),
        ),
    ]
