# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdnNetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdn_net_id', models.CharField(max_length=16, verbose_name='cdn子网编号')),
                ('cdn_top_domain', models.CharField(max_length=20, verbose_name='cdn子网顶级域名')),
                ('top_domain_record_num', models.CharField(max_length=30, verbose_name='cdn子网顶级域名备案号')),
                ('report_status', models.CharField(max_length=1, verbose_name='上报状态')),
                ('report_time', models.CharField(max_length=20, verbose_name='上报时间')),
            ],
            options={
                'verbose_name': 'CDN子网信息',
            },
        ),
    ]
