# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_net_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountCdnNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdn_net_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='cdn子网编号')),
                ('cdn_node_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='cdn节点编号')),
                ('cdn_house_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='cdn机房编号')),
                ('report_status', models.CharField(blank=True, max_length=1, null=True, verbose_name='上报状态')),
                ('report_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='上报时间')),
                ('create_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'CDN节点挂载机房',
            },
        ),
        migrations.AddField(
            model_name='cdnnetinfo',
            name='create_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cdnnetinfo',
            name='cdn_net_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='cdn子网编号'),
        ),
        migrations.AlterField(
            model_name='cdnnetinfo',
            name='cdn_top_domain',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='cdn子网顶级域名'),
        ),
        migrations.AlterField(
            model_name='cdnnetinfo',
            name='report_status',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='上报状态'),
        ),
        migrations.AlterField(
            model_name='cdnnetinfo',
            name='report_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='上报时间'),
        ),
        migrations.AlterField(
            model_name='cdnnetinfo',
            name='top_domain_record_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='cdn子网顶级域名备案号'),
        ),
    ]
