# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_net_info', '0002_auto_20170324_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountCdnDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdn_net_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='cdn子网编号')),
                ('cdn_domain_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='cdn域名编号')),
                ('report_status', models.CharField(blank=True, max_length=1, null=True, verbose_name='上报状态')),
                ('report_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='上报时间')),
                ('create_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'CDN子网挂载加速域名',
            },
        ),
    ]
