# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_net_info', '0003_mountcdndomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountcdnnode',
            name='cdn_house_id',
        ),
    ]
