# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdnNodeHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdn_house_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='机房编号')),
                ('cdn_house_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='机房名称')),
                ('cdn_house_nature', models.CharField(blank=True, max_length=10, null=True, verbose_name='机房属性')),
                ('business_unit', models.PositiveIntegerField(blank=True, null=True, verbose_name='所属经营者单位')),
                ('house_province', models.CharField(blank=True, max_length=20, null=True, verbose_name='机房所在省')),
                ('house_city', models.CharField(blank=True, max_length=20, null=True, verbose_name='机房所在市')),
                ('house_county', models.CharField(blank=True, max_length=20, null=True, verbose_name='机房所在县')),
                ('house_address', models.CharField(blank=True, max_length=40, null=True, verbose_name='机房地址')),
                ('house_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='机房邮编')),
                ('network_people', models.PositiveIntegerField(blank=True, null=True, verbose_name='网络负责人')),
                ('report_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('report_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='上报时间')),
            ],
            options={
                'verbose_name': 'CDN节点机房信息',
            },
        ),
        migrations.CreateModel(
            name='HouseFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_type', models.CharField(blank=True, max_length=1, null=True, verbose_name='使用类型')),
                ('frame_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='机架/机位名称')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdn_node_house.CdnNodeHouse')),
            ],
            options={
                'verbose_name': 'CDN节点机房机架信息',
            },
        ),
        migrations.CreateModel(
            name='HouseIpseg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ip', models.CharField(blank=True, max_length=10, null=True, verbose_name='起始IP')),
                ('end_ip', models.CharField(blank=True, max_length=10, null=True, verbose_name='终止IP')),
                ('ip_use_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='IP地址使用方式')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdn_node_house.CdnNodeHouse')),
            ],
            options={
                'verbose_name': 'CDN节点机房IP地址段信息',
            },
        ),
        migrations.CreateModel(
            name='HouseLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_ip', models.CharField(blank=True, max_length=10, null=True, verbose_name='网关IP地址')),
                ('link_bandwidth', models.PositiveIntegerField(blank=True, null=True, verbose_name='链路带宽')),
                ('link_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='链路类型')),
                ('link_access_unit', models.CharField(blank=True, max_length=30, null=True, verbose_name='接入单位')),
                ('link_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='链路分配时间')),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdn_node_house.CdnNodeHouse')),
            ],
            options={
                'verbose_name': 'CDN节点机房链路信息',
            },
        ),
    ]
