# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_node_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MountCdnHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdn_node_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='cdn节点编号')),
                ('cdn_house_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='cdn机房编号')),
                ('report_status', models.CharField(blank=True, max_length=1, null=True, verbose_name='上报状态')),
                ('report_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='上报时间')),
                ('create_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'CDN节点挂载机房',
            },
        ),
    ]
