# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn_node_info', '0002_mountcdnhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountcdnhouse',
            name='cdn_net_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='cdn子网编号'),
        ),
    ]
