# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='服务编号')),
                ('service_content', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务内容')),
                ('report_status', models.CharField(blank=True, max_length=1, null=True, verbose_name='上报状态')),
                ('report_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='上报时间')),
            ],
            options={
                'verbose_name': '应用服务信息',
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='客户编号')),
                ('unit_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='单位名称')),
                ('unit_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位地址')),
                ('unit_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='单位邮编')),
                ('unit_nature', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位属性')),
                ('id_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='证件类型')),
                ('id_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='证件号码')),
                ('network_people', models.PositiveIntegerField(blank=True, null=True, verbose_name='网络信息安全负责')),
                ('register_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='注册时间')),
                ('business_unit', models.PositiveIntegerField(blank=True, null=True, verbose_name='所属经营者单位')),
                ('report_status', models.CharField(blank=True, max_length=1, null=True, verbose_name='上报状态')),
                ('report_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='上报时间')),
            ],
            options={
                'verbose_name': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='DomainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=16, verbose_name='域名编号')),
                ('domain', models.CharField(max_length=20, verbose_name='域名')),
                ('source_address', models.CharField(max_length=30, verbose_name='源站地址')),
                ('record_num', models.CharField(max_length=30, verbose_name='备案号或许可证号')),
                ('top_domain', models.CharField(max_length=20, verbose_name='顶级域名')),
                ('report_status', models.CharField(blank=True, max_length=1, null=True, verbose_name='上报状态')),
                ('report_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='上报时间')),
                ('app_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_info.AppServiceInfo')),
            ],
            options={
                'verbose_name': '域名信息',
            },
        ),
        migrations.AddField(
            model_name='appserviceinfo',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_info.CustomerInfo'),
        ),
    ]
