# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='单位名称')),
                ('unit_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位地址')),
                ('unit_zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='单位邮编')),
                ('unit_nature', models.CharField(blank=True, choices=[('1', '军队'), ('2', '政府机关'), ('3', '事业单位'), ('4', '企业'), ('5', '个人'), ('6', '社会团体'), ('999', '其他')], max_length=20, null=True, verbose_name='单位属性')),
                ('id_type', models.CharField(blank=True, choices=[('1', '工商营业执照号码'), ('2', '身份证'), ('3', '组织机构代码证书'), ('4', '事业法人证书'), ('5', '军队代号'), ('6', '社团法人证书'), ('7', '护照'), ('8', '军官证'), ('7', '台胞证'), ('999', '其他')], max_length=10, null=True, verbose_name='证件类型')),
                ('id_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='证件号码')),
                ('network_people', models.PositiveIntegerField(blank=True, null=True, verbose_name='网络信息安全负责')),
                ('register_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='注册时间')),
                ('app_service', models.PositiveIntegerField(blank=True, null=True, verbose_name='应用服务')),
                ('business_unit', models.PositiveIntegerField(blank=True, null=True, verbose_name='所属经营者单位')),
                ('user_nature', models.PositiveIntegerField(blank=True, null=True, verbose_name='用户属性')),
                ('status', models.CharField(blank=True, max_length=1, null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '客户信息',
            },
        ),
    ]
