# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('city', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': '用户信息',
            },
        ),
    ]
