# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('id_type', models.CharField(choices=[('1', '工商营业执照号码'), ('2', '身份证'), ('3', '组织机构代码证书'), ('4', '事业法人证书'), ('5', '军队代号'), ('6', '社团法人证书'), ('7', '护照'), ('8', '军官证'), ('7', '台胞证'), ('999', '其他')], max_length=3, verbose_name='证件类型')),
                ('id_number', models.CharField(max_length=20, verbose_name='证件号码')),
                ('tel', models.CharField(max_length=20, verbose_name='固定电话')),
                ('phone', models.CharField(max_length=20, verbose_name='移动电话')),
                ('email', models.CharField(max_length=20, verbose_name='email地址')),
            ],
            options={
                'verbose_name': '网络安全责任人',
            },
        ),
    ]
